# Source: lighthouse/templates/poller-sa.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: lighthouse-poller
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
